### ISSUE TITLE
Error while submitting

### ISSUE THREAD

**Issue by bayweiheng** [cs4246/meta#1]
LumiNUS is down so I can't ask on the forum - posting as an issue instead, hopefully someone will see it.

I am getting the following error while submitting my assignment. I have the correct directory structure, but somehow the runner cannot find a setup file? Could you kindly look into why the runner is like this?

Thanks in advance for the help!

{
-"error": {
"type": "AgentInstallError",
-"args": [
"    ERROR: Command errored out with exit status 1:\n     command: /home/course/cs4246/.pyenv/versions/3.7.2/envs/aiVLE-runner-TS.4-A.91-HT48Q2I8ERXBQPJY7CBG1NY6Y28T5QTT/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-req-build-c9ycuq7i/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-req-build-c9ycuq7i/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base pip-egg-info\n         cwd: /tmp/pip-req-build-c9ycuq7i/\n    Complete output (5 lines):\n    Traceback (most recent call last):\n      File \"&lt;string&gt;\", line 1, in &lt;module&gt;\n      File \"/home/course/cs4246/.pyenv/versions/3.7.2/lib/python3.7/tokenize.py\", line 447, in open\n        buffer = _builtin_open(filename, 'rb')\n    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-c9ycuq7i/setup.py'\n    ----------------------------------------\nERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n"
]
}
}

**Comment by rizkiarm** [comment]
I just checked your submission. Apparently you didn't follow the zipping procedure properly. You introduced ``agent`` folder inside of the zip file, giving:
```
agent.zip
    agent/
        setup.py
        ...
```
Please refer to our FAQ (https://github.com/cs4246/meta/wiki/Frequently-Asked-Questions/_edit#agentinstallexception) and submission guide (https://github.com/cs4246/meta/wiki/Web-Submission#submission) for more details.
